
name: Build wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}-${{matrix.version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        version: ["cp38","cp39","cp310","cp311","cp312","cp313"]
    
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:    
          CIBW_BUILD: ${{matrix.version}}-*
          CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_ARCHS_LINUX: auto64
          CIBW_SKIP: "*musllinux*"
          CIBW_TEST_REQUIRES: numpy
          CIBW_TEST_COMMAND: python -c "import skfmm, sys; sys.exit(skfmm.test())"
          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.version}}-wheel
          path: ./wheelhouse/*.whl


